
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["golang.org/x/tools/cmd/goimports", "github.com/onsi/ginkgo/ginkgo"]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.21"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/greenplum-db/gp-common-go-libs"

[[constraint]]
  name = "github.com/sergi/go-diff"
  version = "1.0.0"
