platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: ccp_src
- name: cluster_env_files
- name: boostfs_installer
- name: pgcrypto43
  optional: true
- name: gpbackup_ddboost_plugin

params:
  DD_SOURCE_HOST:
  DD_USER:
  DD_PW:

run:
  path: gpbackup/ci/scripts/boostfs-install.bash
