---
PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.10.3'

inputs:
 - name: gpbackup
   path: go/src/github.com/greenplum-db/gpbackup
 - name: gpbackup-dependencies

outputs:
- name: output_deps

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH
    mkdir -p $GOPATH/bin

    tar -zxf gpbackup-dependencies/dependencies.tar.gz -C $GOPATH/src/github.com/greenplum-db/gpbackup/

    pushd $GOPATH/src/github.com/greenplum-db/gpbackup
      make depend
      tar cfz dependencies.tar.gz vendor
    popd
    cp $GOPATH/src/github.com/greenplum-db/gpbackup/dependencies.tar.gz output_deps/
