platform: linux

image_resource:
  type: docker-image

inputs:
- name: go_components
- name: ddboost_components_SLES

outputs:
- name: SLES_binaries

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    pushd SLES_binaries
      # Create install script
      printf "#!/bin/sh\nset -x\ntar -xzvf bin_gpbackup.tar.gz -C \$GPHOME" > install_gpdb_component
      chmod +x install_gpdb_component

      cp ../go_components/*_version .
      mv ../go_components/gpbackup_version version
      cp ../ddboost_components_SLES/*_version .

      mkdir -p bin
      cp ../go_components/gpbackup bin/
      cp ../go_components/gpbackup_helper bin/
      cp ../go_components/gprestore bin/
      cp ../go_components/gpbackup_s3_plugin bin/
      cp ../go_components/gpbackup_manager bin/
      cp ../ddboost_components_SLES/gpbackup_ddboost_plugin bin/

      mkdir -p lib
      cp ../ddboost_components_SLES/libDDBoost.so lib/

      tar -czvf bin_gpbackup.tar.gz bin/ lib/

      version=`cat version`
      tar -czvf "gpbackup-${version}.tar.gz" bin_gpbackup.tar.gz install_gpdb_component gpbackup_version version s3_plugin_version ddboost_plugin_version gpbackup_manager_version
    popd
