name: build_and_unit_test

on:
  push:
    branches: [ test-ci ]

jobs:

  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: go/src/github.com/cloudberrydb/gpbackup

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set Environment
      run: |
        echo "GOPATH=/home/runner/work/gpbackup/gpbackup/go" >> $GITHUB_ENV
        echo "/home/runner/work/gpbackup/gpbackup/go/bin" >> $GITHUB_PATH

    - name: Dependencies
      run: |
        cd ${GOPATH}/src/github.com/cloudberrydb/gpbackup
        make depend

    - name: Build
      run: |
        cd ${GOPATH}/src/github.com/cloudberrydb/gpbackup
        make build

    - name: Unit Test
      run: |
        cd ${GOPATH}/src/github.com/cloudberrydb/gpbackup
        make unit_all_gpdb_versions